// apps/my_mercado/src/components/DeviceToolbar.tsx
import { useDeviceUI } from '../hooks/useDeviceUI'

export function DeviceToolbar() {
    const { mode, setMode } = useDeviceUI()
    const isDev = import.meta.env.DEV

    if (!isDev) return null

    const buttons: { mode: 'mobile' | 'tablet' | 'desktop' | 'auto'; icon: string; label: string }[] = [
        { mode: 'mobile', icon: '📱', label: 'Mobile (375px)' },
        { mode: 'tablet', icon: '📲', label: 'Tablet (768px)' },
        { mode: 'desktop', icon: '🖥', label: 'Desktop' },
        { mode: 'auto', icon: '🔄', label: 'Auto' },
    ]

    return (
        <div style={{
            position: 'fixed',
            bottom: 80,
            right: 16,
            display: 'flex',
            gap: 4,
            padding: 8,
            background: '#1e1e1e',
            borderRadius: 10,
            boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
            zIndex: 9999,
        }}>
            {buttons.map((btn) => (
                <button
                    key={btn.mode}
                    onClick={() => setMode(btn.mode)}
                    title={btn.label}
                    style={{
                        padding: '6px 10px',
                        border: `1px solid ${mode === btn.mode ? '#3b82f6' : '#444'}`,
                        borderRadius: 6,
                        background: mode === btn.mode ? '#3b82f6' : 'transparent',
                        color: mode === btn.mode ? '#fff' : '#ccc',
                        fontSize: 16,
                        cursor: 'pointer',
                        transition: 'all 0.15s',
                    }}
                >
                    {btn.icon}
                </button>
            ))}
        </div>
    )
}

// packages/device-ui/packages/vue/src/components/DeviceToolbar.vue
<template>
    <div v-if="visible" class="dui-toolbar">
        <button
            v-for="btn in buttons"
            :key="btn.mode"
            :class="{ active: mode === btn.mode }"
            :title="btn.label"
            @click="setMode(btn.mode)"
        >
            {{ btn.icon }}
        </button>
    </div>
</template>

<script setup lang="ts">
import { useDeviceUI } from '../composables/useDeviceUI'

const { mode, setMode } = useDeviceUI()
const visible = import.meta.env.DEV

const buttons = [
    { mode: 'mobile' as const, icon: '📱', label: 'Mobile' },
    { mode: 'tablet' as const, icon: '📲', label: 'Tablet' },
    { mode: 'desktop' as const, icon: '🖥', label: 'Desktop' },
    { mode: 'auto' as const, icon: '🔄', label: 'Auto' },
]
</script>

<style scoped>
.dui-toolbar {
    position: fixed;
    bottom: 16px;
    right: 16px;
    display: flex;
    gap: 4px;
    padding: 8px;
    background: #1e1e1e;
    border-radius: 10px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
    z-index: 9999;
}

.dui-toolbar button {
    padding: 6px 10px;
    border: 1px solid #444;
    border-radius: 6px;
    background: transparent;
    color: #ccc;
    font-size: 16px;
    cursor: pointer;
    transition: background 0.15s, border-color 0.15s;
}

.dui-toolbar button:hover {
    background: #333;
}

.dui-toolbar button.active {
    background: #3b82f6;
    border-color: #3b82f6;
    color: #fff;
}
</style>
